name: addS3BucketAWS   # This assigns a name to the workflow.
'on': # The workflow runs manually via the GitHub UI (not automatically on push/pull requests).
  workflow_dispatch: null
jobs: # This job defines a single job named build that is running on Ubuntu-latest virtual machine.
  build:
    runs-on: ubuntu-latest
    steps: # Checks out your repository code (though not strictly needed for this S3 operation).
      - uses: actions/checkout@master
      - name: Upload to S3   # Create S3 Bucket.
        run: |
          aws s3 mb s3://<ae-test-bucket-1982honore>
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: us-east-1
