name: Create S3 Bucket
on:
  workflow_dispatch:

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Create S3 Bucket
        run: aws s3 mb s3://ae-test-bucket-1982honore
